- id: '1749931382004'
  name: Salon — Kino
  entities:
    media_player.salon_2:
      assumed_state: true
      device_class: tv
      friendly_name: Salon 2
      supported_features: 153529
      volume_level: 0.2
      is_volume_muted: false
      app_id: com.tcl.tv
      app_name: com.tcl.tv
      state: 'on'
    remote.salon_2:
      activity_list: []
      current_activity: com.tcl.tv
      friendly_name: Salon 2
      supported_features: 4
      state: 'on'
  icon: mdi:account-group
  metadata: {}
- id: '1790000000001'
  name: Czujniki Ruchu — wyłącz automatyczne światło
  icon: mdi:motion-sensor-off
  entities:
    input_boolean.motion_lights_disabled:
      state: 'on'
- id: '1790000000002'
  name: Czujniki Ruchu — włącz automatyczne światło
  icon: mdi:motion-sensor
  entities:
    input_boolean.motion_lights_disabled:
      state: 'off'
