parking_screenshot:
  alias: Parking screenshot
  sequence:
  - action: camera.snapshot
    metadata: {}
    data:
      filename: Parking
    target:
      device_id: 91d2e38b1f538e39d124502873965058
  description: ''
test:
  alias: Test
  sequence: []
  description: ''
nowy_skrypt:
  alias: Nowy skrypt
  sequence: []
  description: ''
nowy_skryptd:
  alias: Nowy skryptd
  sequence:
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      label_id: swiatlo
  description: ''
roller_bedroom_on:
  alias: Roller Bedroom ON
  sequence:
  - type: turn_on
    device_id: ffbfc79a8746e627343698b0cecbdf88
    entity_id: 61a94e2cc0792d6f9b6b66b4815e6c8d
    domain: switch
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - type: turn_off
    device_id: ffbfc79a8746e627343698b0cecbdf88
    entity_id: 61a94e2cc0792d6f9b6b66b4815e6c8d
    domain: switch
  description: ''
